name: Deploy Next.js static export to Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  APP_DIR: my-portfolio   # <-- change if needed

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.APP_DIR }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ${{ env.APP_DIR }}/package-lock.json

      # Use npm ci if lockfile exists; otherwise npm install
      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then
            npm ci --no-audit --no-fund
          else
            npm install --no-audit --no-fund
          fi

      # ⬅️ This alone produces ./out because next.config has output:"export"
      - name: Build (static export)
        run: npm run build

      # Make sure GitHub Pages serves underscored folders like _next/
      - name: Add .nojekyll to out
        run: touch out/.nojekyll

      # Ensure CNAME is present (if you keep it in /public)
      - name: Ensure CNAME copied
        run: |
          if [ -f public/CNAME ] && [ ! -f out/CNAME ]; then
            cp public/CNAME out/CNAME
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.APP_DIR }}/out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
